### ISSUE TITLE
SSH Connection to Slave Error

### ISSUE THREAD

**Issue by AdnaneKhan** [maxfields2000/dockerjenkins_tutorial#17]
```
07/06/16 17:52:51] [SSH] Opening SSH connection to 192.168.99.100:32792.
ERROR: Server rejected the 1 private key(s) for jenkins (credentialId:f89770c5-b0d6-411b-b348-3c0c63b89c4d/method:publickey)
ERROR: Failed to authenticate as jenkins with credential=f89770c5-b0d6-411b-b348-3c0c63b89c4d
java.io.IOException: Publickey authentication failed.
    at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:315)
    at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:467)
    at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.doAuthenticate(TrileadSSHPublicKeyAuthenticator.java:109)
    at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.authenticate(SSHAuthenticator.java:408)
    at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.authenticate(SSHAuthenticator.java:428)
    at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1173)
    at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:701)
    at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The connection is closed.
    at com.trilead.ssh2.auth.AuthenticationManager.deQueue(AuthenticationManager.java:63)
    at com.trilead.ssh2.auth.AuthenticationManager.getNextMessage(AuthenticationManager.java:86)
    at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:290)
    ... 11 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
    at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
    at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
    at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
    at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:693)
    at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:489)
    ... 1 more
[07/06/16 17:52:51] [SSH] Authentication failed.
hudson.AbortException: Authentication failed.
    at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1178)
    at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:701)
    at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[07/06/16 17:52:51] Launch failed - cleaning up connection
[07/06/16 17:52:51] [SSH] Connection closed.
```

When the jenkins master attempts to connect to the slave I get the following error in the log. I've double checked that the correct public key is in the authorized_keys file. In addition if I try to connect directly I get:

```
System is booting up. See pam_nologin(8)
```

The keypair I am using was generated using the `ssh-keygen -t rsa` command on my host machine.

**Comment by AdnaneKhan** [comment]
I was able to work around this issue by adding 

```
RUN rm -f /run/nologin
```

at the end of the Dockerfile for the jenkins slave.

**Comment by cirocosta** [comment]
Hey @AdnaneKhan , thanks for the suggestion. Had the same error here and adding the removal of `/run/nologin` did the job 👍 
Also, on the slave's `sshd` side, after running `rsyslogd` inside the slave you can check that (before removing the `nologin`) we get:

```
Jul  7 19:49:19 aba7116ed670 sshd[20]: fatal: Access denied for user jenkins by PAM account configuration [preauth]
```

**Comment by maxfields2000** [comment]
Neat find. Is this happening for you right out of the box with what I have or by any chance are you changing versions on anything?

Last time I tested things seemed to work so I'll go figure out what's changed. This looks like a good update so worst case I'll apply this to the build slave image permanently.  Going to leave this issue open until I'm confident things just work out of the box one way or another.  Thanks for coming back with what you found fixed it!

**Comment by AdnaneKhan** [comment]
Pretty much out of the box. I had updated the Jenkins version however this issue still manifested itself with the following set of steps to take Jenkins out of the mix.

While in jenkins-slave directory:

```
docker build .
```

```
docker run {IMAGE_ID}
```

```
ssh -i files/dummy_private_rsa_key jenkins@172.17.0.3
```

The result is then:

```
The authenticity of host '172.17.0.3 (172.17.0.3)' can't be established.
ECDSA key fingerprint is 6b:c0:6e:c6:e8:0e:75:68:3c:05:32:0e:ba:df:40:de.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.17.0.3' (ECDSA) to the list of known hosts.
System is booting up. See pam_nologin(8)
Connection closed by 172.17.0.3
```

I tried this using both Docker installed directly on my CentOS 7 host, as well in the docker machine running Boot2Docker.

The Docker version I am using is 1.11.1

**Comment by CosetteN** [comment]
I'm having the same issue, but adding @AdnaneKhan's fix to the end of the slave file didn't alter anything.  Could it be linked to using Docker version 1.12.2?

**Comment by De1taE1even** [comment]
This solution worked for me as well, thanks so much!  For reference, I'm running docker version 1.13.1.

**Comment by maxfields2000** [comment]
Still plan on including this in my update, though On Jenkins2 I've switched to the JNLP launcher (from Yet another docker plugin) and SSH is no longer needed but I'll get the Jenkins 1.6'ish version fixed.

**Comment by SalahAdDin** [comment]
Will you make a new tutorial for it?  You are speaking about [this](https://github.com/jenkinsci/docker-jnlp-slave), right?

**Comment by maxfields2000** [comment]
Working on a new tutorial but yes, it's all fixed in the Jenkins2 folder (I'm moving on from Jenkins 1 finally!)
