### ISSUE TITLE
tutorial_01 crashes with Jenkins 2

### ISSUE THREAD

**Issue by aksakalli** [maxfields2000/dockerjenkins_tutorial#22]
Since **tutorial_01** does not have a tag like in other **Dockerfile**s it pulls the latest Jenkins version, which is 2.7.2 and crashes with the following error:

```
can@can: ~/dockerjenkins_tutorial/tutorial_01$ docker logs jenkins-master 
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at Main._main(Main.java:246)
    at Main.main(Main.java:91)
Caused by: java.lang.IllegalArgumentException: Unrecognized option: --handlerCountStartup=100
    at winstone.cmdline.CmdLineParser.parse(CmdLineParser.java:53)
    at winstone.Launcher.getArgsFromCommandLine(Launcher.java:359)
    at winstone.Launcher.main(Launcher.java:332)
```

The latest version of Jenkins is not compatible with this tutorial, so the version should be specified for **tutorial_01**.

**Comment by aksakalli** [comment]
#23 merged
